In [1]:
import numpy as np

In [2]:
a = np.array([1,2 ,3], dtype = "int16")
print(a)

[1 2 3]


In [5]:
b = np.array([[1.0 ,2.0 ,3.0], [4.0 ,5.0 ,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
#get dimension
b.ndim

2

In [9]:
#get shape
b.shape

(2, 3)

In [11]:
#get size
b.size

3

In [14]:
#get type
a.dtype

dtype('int16')

In [15]:
#get total size
a.nbytes

6

In [17]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a[1,5]

13

In [19]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
a[:, 2]

array([ 3, 10])

In [22]:
a[0, 1:-1:2]

array([2, 4, 6])

In [24]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [26]:
a[:,2] = [1,5]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [27]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
print(b[0,1,1])

4


In [30]:
b[:,1,:] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((4,4),  dtype = "int32")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
np.ones((4,2,2), dtype = "int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [39]:
np.full(a.shape, 99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [41]:
np.random.rand(4,2)

array([[0.04020608, 0.3106938 ],
       [0.63347502, 0.87325163],
       [0.58325855, 0.69922912],
       [0.58508099, 0.7702228 ]])

In [46]:
np.random.randint(-1, 1, size=  (3,3))

array([[ 0,  0,  0],
       [-1, -1,  0],
       [ 0, -1, -1]])

In [48]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 1)
#axis = 0 means col 1 means row
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [57]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

output[1:-1, 1:-1] = z
output[2, 2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
